config/routes.rb
Rails.application.routes.draw do

  resources :users 

  
  root 'welcome#index'

  post '/login' => 'sessions#create'

  post '/logout' => 'sessions#destroy'

  get '/articles' => 'articles#index', as: :articles 

  get '/articles/new' => 'articles#new', as: :new_article

  post '/articles' => 'articles#create', as: :create_article

  get '/articles/:id' => 'articles#show', as: :article 

  get '/articles/:id/edit' => 'articles#edit', as: :edit_article

  patch '/articles/:id' => 'articles#update'

  delete '/articles/:id' => 'articles#destroy'

  get '/articles/:article_id/comments' => 'comments#index', as: :article_comments

  get '/articles/:article_id/comments/new' => 'comments#new', as: :new_article_comment

  post '/articles/:article_id/comments' => 'comments#create'

  get '/articles/:article_id/comments/:id' => 'comments#show', as: :article_comment 

  get '/articles/:article_id/comments/:id/edit' => 'comments#edit'

  put '/articles/:article_id/comments/:id' => 'comments#update'

  delete '/articles/:article_id/comments/:id' => 'comments#destroy'

end

app/models/article.rb
class Article < ActiveRecord::Base
	belongs_to :user
	has_many :comments, dependent: :destroy
	validates :title, presence: true, 
										length: { minimum: 5}
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :article
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :articles 
	has_many :comments

	validates :username, :email, :password, presence: true

	def password=(pass_input)
		self.hashed_password = BCrypt::Password.create(pass_input)
	end

	def password
		@password = BCrypt::Password.new(self.hashed_password)
	end

	def self.authenticate(email_input, pass_input)
		user = User.find_by_email(email_input)
		return user if user && user.password == pass_input
		nil 
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
	http_basic_authenticate_with name: 'dhh', password: 'secret', 
except: [:index, :show]

	def index
		@articles = Article.all
	end

	def new
		@article = Article.new
	end

	def create
		user = User.find(session[:id])
		@article = Article.new(article_params)

		if	@article.save
			user.articles << @article 
			redirect_to @article 
		else
			render 'new'
		end
	end

	# def create
	#   article = Article.new
	#   article.created_by = current_user.id # `created_by` tracks which user authored the article
	#   article.attributes = params[:article]
	#   article.save

	#   redirect_to articles_url
	# end

	def show
		@article = Article.find(params[:id])
	end

	def edit
		@article = Article.find(params[:id])
	end

	def update
		@article = Article.find(params[:id])
		if @article.update(article_params)
			redirect_to @article
		else
			render 'edit'
		end
	end

	def destroy
		@article = Article.find(params[:id])
		@article.destroy

		redirect_to articles_path 
	end

	private
		def article_params
			params.require(:article).permit(:title, :text)
		end
	#odd styling in the tutorial. Seems like you wouldn't want to indent
	#the private methods here. 
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	http_basic_authenticate_with name: 'dhh', password: 'secret',
only: :destroy

	def create
		user = User.find(session[:id])
		@article = Article.find(params[:article_id])
		@comment = @article.comments.create(comment_params)
		user.comments << @comment
		redirect_to article_path(@article)
	end

	def destroy
		article = Article.find(params[:article_id])
		comment = article.comments.find(params[:id])
		comment.destroy
		redirect_to article_path(article)
	end

	private
		def comment_params
			params.require(:comment).permit(:commenter, :body)
		end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	def create
		if user = User.authenticate(params[:user][:email], params[:user][:password])
			session[:id] = user.id
			redirect_to "/users/#{user.id}"
		else
			@errors = "invalid email or password"
			render "welcome/index"
		end		
	end

	def destroy
		session[:id] = nil 
		redirect_to "/"
	end	
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def index
		@users = User.all
	end


	def create
		@user = User.new(user_params)
		if @user.save
			session[:id] = @user.id
			redirect_to "/users/#{@user.id}"
		else
			@errors = @user.errors.full_messages
			render 'welcome/index'
		end
	end

	def show
	 @user = User.find(params[:id])
	end

	private

		def user_params
			params.require(:user).permit(:username, :password, :email)
		end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def create
  	@user = User.new(params[:user])
  	if @user.save 
  		session[:id] = user.id
  		redirect_to "/users/#{@user.id}"
  	else
  		@errors = @user.errors.full_messages
  	end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/_form.html.erb
  <%= form_for (@article, remote: true) html: {:class => 'form'} do |f| %>
   
    <% if @article.errors.any? %>
      <div id="error_explanation">
        <h2>
          <%= pluralize(@article.errors.count, "error") %> prohibited
          this article from being saved:
        </h2>
        <ul>
          <% @article.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
   
    <p>
      <%= f.label :title %><br>
      <%= f.text_field :title %>
    </p>
   
    <p>
      <%= f.label :text %><br>
      <%= f.text_area :text %>
    </p>
   
    <p>
      <%= f.submit %>
    </p>
   
  <% end %>

app/views/articles/edit.html.erb
<h1>Editing article</h1>
 
<%= render 'form' %>
 
<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<h1>Listing articles</h1>

<div class= "container">
<table class="article">
	<% @articles.each do |article| %>


			
			<tr>
				<td><h3><%= article.title %></h3></td>
				<td><p><%= article.text %></p></td>
				<td><strong><%= article.user.username %></strong></td>
				<td><%= link_to "show", article_path(article) %></td>
				<% if article.user.id == session[:id] %>
					<td><%= link_to "edit", edit_article_path(article) %></td>
					<td><%= link_to "destroy", article_path(article),
																			method: :delete,
																			data: {confirm: 'Are you sure?'} %></td>
				<% end %>
			</tr>
		<% end %>
	</table>
</div>

<%= link_to "New Article", new_article_path %>

app/views/articles/new.html.erb
<h1>New Article</h1>

<%= render 'form' %>

<%= link_to 'Back', articles_path %>

app/views/articles/show.html.erb
<div class = "container">
	<div class = "article">
		<h1 class="title">
			<%= @article.title %>
		</h1>

		<p class='body'>
			<%= @article.text %>
		</p>

		<p class='author'>
			<strong>Author:</strong><br>
			<%= @article.user.username %>
		</p>
	</div>
	<h2>Comments</h2>

	<%= render @article.comments %> 

	<h2>Add a comment</h2>
	

		<%= render 'comments/form' %>


	<% if @article.user.id == session[:id] %>
		<%= link_to_if(@article.user.id == session[:id],'Edit', edit_article_path(@article))	%>
	<% end %>
	<%= link_to 'Back', articles_path %>
</div>

app/views/comments/_comment.html.erb
<div class = "comment">
	<p>
		<strong>Commenter:</strong>
		<% if comment.user %>
			<%= comment.user.username %>
		<% end %>
	</p>

	<p>
		<strong>Comment:</strong>
		<%= comment.body %>
	</p>

	<p>
		<% if comment.user %>
			<% if comment.user.id == session[:id] || comment.article.user.id == session[:id] %>
				<%= link_to 'Destroy Comment', [comment.article, comment],
					method: :delete,
					data: {confirm: 'Are you sure?'} %>
			<% end %>
		<% end %>
	</p>
</div>

app/views/comments/_form.html.erb
<%= form_for([@article, @article.comments.build]) do |f| %>

<p>
	<%= f.label :body %><br>
	<%= f.text_area :body %>
</p>

<p>
	<%= f.submit %>
</p>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Awesome Blog</title>
  <%= stylesheet_link_tag    'application', media: 'all'%>
  <%= javascript_include_tag 'application'%>
  <%= csrf_meta_tags %>
</head>
<body>
	<header>
		<% if session[:id] != nil %>
			<ul>
				<li><%= link_to_unless_current("main", articles_path) %></li>
				<li><%= link_to "logout", logout_path, method: 'destroy' %></li>
			</ul>
		<% end %>
		<h1>Blog!</h1>
	</header>
<%= yield %>

</body>
</html>

app/views/users/show.html.erb
<% if @user.id == session[:id] %>
	<div class="container">
	<h1>Hello, <%= @user.username %>!</h1>
	<%= link_to 'add article', new_article_path %>
	</div>
<% end %>

<% if @user.articles.any? %>
	<% @user.articles.each do |article| %>
	<div class="container">
		<div class = "article">
			<h1><%= article.title %></h1>
			<p><%= article.text %></p>
			<p><%= article.created_at %></p>
		<% end %>
		</div>
	</div>
<% end %>

app/views/welcome/index.html.erb
<h1>Welcome!</h1>
<h1>Register</h1>
<% if session[:id] == nil %>
	<%= form_for :user, url: '/users' do |f| %>
		<p>
			<%= f.label :username %>
			<%=	f.text_field :username %>
		</p>

		<p>
			<%= f.label :email %>
			<%= f.text_field :email %>
		</p>

		<p>
			<%= f.label :password %> 
			<%= f.password_field :password %>			
		</p>

		<p>
			<%= f.submit %>
		</p>
	<% end %> 
<% end %> 

<h1>Login</h1>
<% if session[:id] == nil %>
	<%= form_for :user, url: '/login' do |f| %>
		<p>
			<%= f.label :email %>
			<%= f.text_field :email %>
		</p>

		<p>
			<%= f.label :password %>
			<%= f.password_field :password %>
		</p>

		<p>
			<%= f.submit 'login' %>
		</p>
	<% end %>
<% end %>

<% if @errors %>
	<%= @errors %>
<% end %>